### PR TITLE
invoke clang with --verbose

### PR DESCRIPTION
**Pull request by ghost**
In theory\* this should run clang with -v at buildtime, which makes it easier to debug.

If this behavior is not desired, disregard this PR.

*I don't know much about tup.

### CODE REVIEW

**Comment by HalosGhost** [comment]
Well, no worries about compatibility with `tup`, you did that perfectly. As for debugging, what case in particular would this help with?

**Comment by ghost** [comment]
In case something fails when someone builds it with the recently introduced "make simple", it would help to figure out what exactly failed. I don't know if my perspective as a packager is not so generic and  if a verbose build output would not be desired for other purposes.

I'm trying to figure out at the moment why exactly ../dist/pbpst is never created.
clang with -v helps a bit.

**Comment by ghost** [comment]
I'm not so sure. On the one hand I think this should be default, on the other there's the configure file which already allows passing on custom CFLAGS.

What do you think?

**Comment by HalosGhost** [comment]
Indeed, since we already allow custom `CFLAGS`, I am disinclined to merge. Closing for now; if someone has a solid reason we should merge it afterall, I will gladly reconsider.

**Pull request closed without merging**
